# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x0eiic3103.llm.v1\"D\n\x04Tool\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x19\n\x11input_schema_json\x18\x03 \x01(\t\"@\n\x0c\x46unctionCall\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\"Q\n\x0e\x46unctionResult\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bresult_json\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\x10\n\x08is_error\x18\x04 \x01(\x08\"\xf0\x01\n\x07Message\x12*\n\x04role\x18\x01 \x01(\x0e\x32\x1c.iic3103.llm.v1.Message.Role\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x34\n\x0e\x66unction_calls\x18\x03 \x03(\x0b\x32\x1c.iic3103.llm.v1.FunctionCall\x12\x38\n\x10\x66unction_results\x18\x04 \x03(\x0b\x32\x1e.iic3103.llm.v1.FunctionResult\";\n\x04Role\x12\x14\n\x10ROLE_UNSPECIFIED\x10\x00\x12\x08\n\x04USER\x10\x01\x12\t\n\x05MODEL\x10\x02\x12\x08\n\x04TOOL\x10\x03\"a\n\x0fGenerateRequest\x12)\n\x08messages\x18\x01 \x03(\x0b\x32\x17.iic3103.llm.v1.Message\x12#\n\x05tools\x18\x02 \x03(\x0b\x32\x14.iic3103.llm.v1.Tool\"T\n\nTokenUsage\x12\x15\n\rprompt_tokens\x18\x01 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x02 \x01(\x05\x12\x14\n\x0ctotal_tokens\x18\x03 \x01(\x05\"\xb2\x01\n\x10GenerateResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x34\n\x0e\x66unction_calls\x18\x02 \x03(\x0b\x32\x1c.iic3103.llm.v1.FunctionCall\x12\r\n\x05model\x18\x03 \x01(\t\x12\x12\n\nlatency_ms\x18\x04 \x01(\x05\x12)\n\x05usage\x18\x05 \x01(\x0b\x32\x1a.iic3103.llm.v1.TokenUsage\x12\x0c\n\x04stop\x18\x06 \x01(\x08\x32T\n\x03Llm\x12M\n\x08Generate\x12\x1f.iic3103.llm.v1.GenerateRequest\x1a .iic3103.llm.v1.GenerateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOOL']._serialized_start=29
  _globals['_TOOL']._serialized_end=97
  _globals['_FUNCTIONCALL']._serialized_start=99
  _globals['_FUNCTIONCALL']._serialized_end=163
  _globals['_FUNCTIONRESULT']._serialized_start=165
  _globals['_FUNCTIONRESULT']._serialized_end=246
  _globals['_MESSAGE']._serialized_start=249
  _globals['_MESSAGE']._serialized_end=489
  _globals['_MESSAGE_ROLE']._serialized_start=430
  _globals['_MESSAGE_ROLE']._serialized_end=489
  _globals['_GENERATEREQUEST']._serialized_start=491
  _globals['_GENERATEREQUEST']._serialized_end=588
  _globals['_TOKENUSAGE']._serialized_start=590
  _globals['_TOKENUSAGE']._serialized_end=674
  _globals['_GENERATERESPONSE']._serialized_start=677
  _globals['_GENERATERESPONSE']._serialized_end=855
  _globals['_LLM']._serialized_start=857
  _globals['_LLM']._serialized_end=941
# @@protoc_insertion_point(module_scope)
